services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/aplazo_db
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - '8080'

  mysqldb:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=aplazo_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
    expose:
      - '3306'
volumes:
  mysql-data:
